### PR TITLE
Added library from the main repository

### PR DESCRIPTION
**Pull request by GurliGebis**
This is the library of the main repository.

Ref: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13389

### CODE REVIEW

**Comment by donho** [comment]
@GurliGebis 
2 questions:
1. Is it identical as PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13389 ?
2. You said ["the 32bit installer installs the 32bit DLL on 64bit windows.
It needs to install the 64bit dll on 64bit windows "](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13389#issuecomment-1481782736). However, the old NppShell.dll 32 bits works well under Windows 64 bits. So it should not be the restriction.

**Comment by GurliGebis** [comment]
@donho it is identical, only difference is an unused struct I forgot to remove before.
With this new way, we have to match the installed dll to the architecture, since it is loaded into the explorer process.
If the 32bit dll is installed in 64bit windows, it installs fine (Since the code is run seperately) but it fails when explorer tries to load it.
That is why I changed the install script to deploy the dll matching the taget architecture for the 32bit installer

**Comment by GurliGebis** [comment]
My guess is that the way IExplorerCommand objects are used means it has to match

**Comment by donho** [comment]
> With this new way, we have to match the installed dll to the architecture, since it is loaded into the explorer process.
If the 32bit dll is installed in 64bit windows, it installs fine (Since the code is run seperately) but it fails when explorer tries to load it.

It shouldn't.

> That is why I changed the install script to deploy the dll matching the taget architecture for the 32bit installer.

In PR #13389 ? AFAICS, the modification in NSIS script of pr #13389 is the same way. So in RC5 installer 32 bits deploys always the 
32 bits of NppShell.dll.

**Comment by GurliGebis** [comment]
Why it didn't work I don't know. So if it is a hard requirement to have the 32bit dll loaded into 64bit Windows, I don't know what to do.

The last changes I pushed that you included in RC5 deploys the architecture matching dll, so it loads correctly:
https://github.com/notepad-plus-plus/notepad-plus-plus/compare/4f4b53dbb60999225be39da054065ff4e25aec58..d6b7039834007cc701b5eb79636037fc95bfae77

Why is it important to deploy the 32bit dll on 64bit Windows? (the dll only integrates with explorer, which is 64bit anyway)

**Comment by donho** [comment]
```

	!ifdef ARCH64
		File /oname=$INSTDIR\NppShell.msix "..\bin64\NppShell.msix"
		File /oname=$INSTDIR\NppShell.dll "..\bin64\NppShell.x64.dll"
	!else ifdef ARCHARM64
		File /oname=$INSTDIR\NppShell.msix "..\binarm64\NppShell.msix"
		File /oname=$INSTDIR\NppShell.dll "..\binarm64\NppShell.arm64.dll"
	!else
		; We need to test which arch we are running on, since 32bit exe can be run on both 32bit and 64bit Windows.
		${If} ${RunningX64}
    		File /oname=$INSTDIR\NppShell.dll "..\bin64\NppShell.x64.dll"
		${Else}
    		File /oname=$INSTDIR\NppShell.dll "..\bin\NppShell.x86.dll"
		${EndIf}    

	!endif
```

Here `ARCH64` & `ARCHARM64` are defined in [packageAll.bat](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/v8.5.1/PowerEditor/installer/packageAll.bat#L487), that's how they are built statically in NSIS.

I just don't see the advantage to break such logic since it works perfectly in v8.5.1 and previous versions.

**Comment by GurliGebis** [comment]
8.5.1 didn't have the old context menu using the new implementation, since it is based on RC2, and it was introduced in RC3 🙂
RC3 is where the unification process started, which causes the architecture dependency it seems.

**Comment by donho** [comment]
> Why is it important to deploy the 32bit dll on 64bit Windows?

Good question.
The answer is "due to the auto-update mechanism":
When auto-update is triggered, each different architecture of binary (notepad++.exe) will download the same architecture of installer. And since Notepad++ has been installed into a lot of PC, it's crucial to keep such way.

**Comment by GurliGebis** [comment]
So the auto update doesn't download the newest installer?

**Comment by GurliGebis** [comment]
Which will deploy the 64bit dll, which is fine, since the auto update doesn't look at it

**Comment by GurliGebis** [comment]
I see it does this, so it is not a problem - lets take this use case:
User1 has a Windows 10 64bit pc, with notepad++ 32bit version 8.4.x installed.
When they start notepad++, it notices the update and downloads the 32bit installer and runs it.
The installer detects 64bit Windows and installs the 64bit dll.

So, even when upgrading, it will "just work", since it just picks the correct dll to deploy upon installing/updating 😃

**Comment by donho** [comment]
> If it does, and just looks at the architecture of the notepad++.exe, we should be fine, since it will download the 32bit installer then
> Which will deploy the 64bit dll, which is fine, since the auto update doesn't look at it

I don't see how - 32 bits installer contains only 32 bits NppShell.dll

> User1 has a Windows 10 64bit pc, with notepad++ 32bit version 8.4.x installed.
When they start notepad++, it notices the update and downloads the 32bit installer and runs it.
The installer detects 64bit Windows and installs the 64bit dll.

Could you point me out in PR #13389, where the installer detects 64bit Windows and installs the 64bit dll?

**Comment by GurliGebis** [comment]
Both should be included in the installer, like the old NppShell_06 file - as far as I can see, both are included.
The changes in this commit detects the arch it is running on: https://github.com/notepad-plus-plus/notepad-plus-plus/compare/4f4b53dbb60999225be39da054065ff4e25aec58..d6b7039834007cc701b5eb79636037fc95bfae77

**Comment by donho** [comment]
Yes, you're right - I've forgotten this part and I didn't read this part of code.
Thank you for your patience and your explanation.

**Comment by GurliGebis** [comment]
@donho no worries, and you are very welcome 🙂
Once this is merged, I'll get to work on the few changes needed with the cleanup there

**Comment by donho** [comment]
@GurliGebis 
> I'll get to work on the few changes needed with the cleanup there

Sounds good. Once it's done, please create a PR on notepad-plus-plus repo for retaking the packageAll.bat & nppSetuo.nsi so I will create the new package for testing.

**Pull request closed without merging**
