### PR TITLE
Improved cleanup script, to not move the file away, but just schedule them for deletion on next reboot

### PR DESCRIPTION
**Pull request by GurliGebis**
This improves upon #14 by scheduling the files to be deleted on the next reboot.
It also unregisters the old menu on Windows 11, since we have double entries otherwise.

### CODE REVIEW

**Comment by donho** [comment]
@GurliGebis 
Thank you for the PR.
Please check out the TEST12 here:
http://download.notepad-plus-plus.org/repository/MISC/nppShell.TEST12/

ps: It's OK for this time, but please always create a new branch for a new PR in the future.

**Comment by donho** [comment]
Test results of updating from v8.4.9 (NppShell_06.dll) to TEST12 (new NppShell.dll):

*   Windows 8.1 Pro 64-bits: **test in progress**
*   Windows 10 Pro 64-bits: **test in progress**
*   Windows 11 Home 64-bits: **PASSED**

**Comment by GurliGebis** [comment]
@donho I created a new branch for this based on the master branch? (Or am I misunderstanding?)

**Comment by GurliGebis** [comment]
I just tested on Windows 11, seems to be working, testing on Windows 10 as we speak 🙂

**Comment by GurliGebis** [comment]
Windows 10 test installing 8.4.9 and then upgrading to TEST12:

- NppShell_06.dll is still there, and the right click menu still works.
- Rebooting
- After rebooting, NppShell_06.dll is gone (like it should) and the menu is still working, since now NppShell.dll has taken over.

I think this is finally working.

**Comment by donho** [comment]
Bravo @GurliGebis! You did it!
Yes, I think we have done.
I'll do v8.5.2 RC  this weekend.

Thank you again for fixing that.

**Comment by GurliGebis** [comment]
@donho can you merge this, close the #14 PR (just to cleanup), and then create a new installer where the msix xml tag is removed from `notepad++.exe.manifest`

There seems to be some issues with it and people who have services disabled.
From what I can see, we should be able to run without it, but I would like a TEST13 if possible with it disabled, to get people to verify that it works without it 🙂

I'm thinking about these two:
* notepad-plus-plus/notepad-plus-plus#13446
* notepad-plus-plus/notepad-plus-plus#13457

**Comment by GurliGebis** [comment]
From what I can read, the msix tag is only relevant in the application manifest, if the application is distributed within an MSIX package, which we aren't doing.

**Comment by donho** [comment]
@GurliGebis 
> I created a new branch for this based on the master branch? (Or am I misunderstanding?)

Yes.

**Comment by donho** [comment]
> create a new installer where the msix xml tag is removed from `notepad++.exe.manifest`

Are you talking about the following tag to be removed?
```
<msix xmlns="urn:schemas-microsoft-com:msix.v1"
    publisher="CN=Notepad++, O=Notepad++, L=Saint Cloud, S=Ile-de-France, C=FR"
    packageName="NotepadPlusPlus"
    applicationId="NotepadPlusPlus"
/>
```

**Comment by GurliGebis** [comment]
> > create a new installer where the msix xml tag is removed from `notepad++.exe.manifest`
> 
> Are you talking about the following tag to be removed?
> 
> ```
> <msix xmlns="urn:schemas-microsoft-com:msix.v1"
>     publisher="CN=Notepad++, O=Notepad++, L=Saint Cloud, S=Ile-de-France, C=FR"
>     packageName="NotepadPlusPlus"
>     applicationId="NotepadPlusPlus"
> />
> ```

Exactly, I would like to see if everything still works without it (it should) and if it solves those two issues (it might - they will have to test)

**Comment by GurliGebis** [comment]
I have to go cook dinner, I'll be back later tonight - if you can build TEST13 with that one removed, please update those two issues and ask them to test with that one (after verifying that it works on Windows 11 with it removed).

**Comment by donho** [comment]
@GurliGebis 
TEST13 is ready here:
http://download.notepad-plus-plus.org/repository/MISC/nppShell.TEST13/

FYI, due to notepad++.exe.manifest has been modified, all the notepad++.exe binaries are recompiled.

Please let me know if these packages work as expected.

**Comment by GurliGebis** [comment]
@donho they work as expected, and even work with those two services disabled.
So it would say it is safe to merge this PR and then do another one that cleans up the manifest file in the other repo.

**Comment by GurliGebis** [comment]
I'm closing this PR, since it has been merged in 9efecd71bad1d5a0278aa5fce401a1f44a3a8f2a

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/nppShell/commit/9efecd71bad1d5a0278aa5fce401a1f44a3a8f2a

**Pull request closed without merging**
