### PR TITLE
More logging

### PR DESCRIPTION
**Pull request by GurliGebis**
This adds more logging, to help debug issues with the context menu

### CODE REVIEW

**Comment by GurliGebis** [comment]
@donho this adds more logging and fixes a potential race condition.
Can you merge it, and create a test installer, including the new DLL, to help debug?

**Comment by donho** [comment]
@GurliGebis 
no problem to create the Installer, but could we let user test it before then there might be more evolution in this PR?

**Comment by donho** [comment]
@GurliGebis 
Here are signed installer binaries which contain NppShell of this PR:
http://download.notepad-plus-plus.org/repository/MISC/nppShell_more_log/

**Comment by GurliGebis** [comment]
@donho thanks, I'll use it to debug some more.
You might want to merge it, since it adds more debugging, and fixes a race condition.

**Comment by donho** [comment]
@GurliGebis 
> You might want to merge it, since it adds more debugging, and fixes a race condition.

Merged. Thank you for the PR.
Please thinking of clean up the logs, once the issues are fixed.

**Comment by GurliGebis** [comment]
@donho since it is disabled normally, I don't think removing it is needed?

**Comment by donho** [comment]
@GurliGebis 
If the issue is fixed, it means the log is no more needed. For the sake of facility of maintenance, it's always good to clean up the code. Don't you think so?

**Comment by GurliGebis** [comment]
@donho Keeping it would make sense for this, since it would be easy to have people enable it later on, if other issues with this shows up.
I just there was a way to ensure that there modern command is also shown in the classic menu, it would be great - but people seems to mess around with stuff way too much for that to be stable (like trying to remove the modern right click menu using registry hacks).

**Comment by donho** [comment]
@GurliGebis 
OK. I see your point.
Let it be then. Thank you for your explanation!

**Pull request closed without merging**
